export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCES = "CREATE_ORDER_SUCCES";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

export const MYORDERS_REQUEST = "MYORDERS_REQUEST";
export const MYORDERS_SUCCES = "MYORDERS_SUCCES";
export const MYORDERS_FAIL = "MYORDERS_FAIL";

export const MYORDERS_DETAILS_REQUEST = "MYORDERS_DETAILS_REQUEST";
export const MYORDERS_DETAILS_SUCCES = "MYORDERS_DETAILS_SUCCES";
export const MYORDERS_DETAILS_FAIL = "MYORDERS_DETAILS_FAIL";

export const CLEAR_ERROR = "CLEAR_ERROR";
