export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCES = "ALL_PRODUCT_SUCCES";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCES = "PRODUCT_DETAILS_SUCCES";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const NEW_PRODUCT_REQUEST = "NEW_PRODUCT_REQUEST";
export const NEW_PRODUCT_SUCCES = "NEW_PRODUCT_SUCCES";
export const NEW_PRODUCT_FAIL = "NEW_PRODUCT_FAIL";

export const NEW_PRODUCT_RESET = "NEW_PRODUCT_RESET";

export const NEWREVIEW_REQUEST = "NEWREVIEW_REQUEST";
export const NEWREVIEW_SUCCES = "NEWREVIEW_SUCCES";
export const NEWREVIEW_FAIL = "NEWREVIEW_FAIL";
export const NEWREVIEW_RESET = "NEWREVIEW_RESET";

export const CLEAR_ERROR = "CLEAR_ERROR";
// export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST"
// export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST"
